
classdef msg_cm < ros.Message
    %msg_cm MATLAB implementation of cm/msg_cm
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cm/msg_cm' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '51e1ed7c5e784b847030fbe04b6e407c' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Name' 'Position' 'Temperature' 'Voltage' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'name' 'position' 'temperature' 'voltage' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Name
        Position
        Temperature
        Voltage
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'msg_cm', 'Header')
            obj.Header = val;
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'msg_cm', 'Name');
            obj.Name = cell(val);
        end
        function set.Position(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'msg_cm', 'Position');
            obj.Position = double(val);
        end
        function set.Temperature(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'msg_cm', 'Temperature');
            obj.Temperature = double(val);
        end
        function set.Voltage(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'msg_cm', 'Voltage');
            obj.Voltage = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cm.msg_cm.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cm.msg_cm(strObj);
        end
    end
end
